### ISSUE TITLE
Weird dllist behaviour

### ISSUE THREAD

**Issue by joshuahellier** [rgsoda/pypy-llist#3]
Hey guys, no idea if this is being maintained still, but here goes. I wanted to use your doubly-linked-list module because I need one for an algorithm. I was doing some tests. Try the following code:

`import pyllist
dllist = pyllist.dllist

a = dllist([2.0])
for i in a:
    print(i)
print("\n")
a.appendleft(1.0)
for i in a:
    print(i)
print("\n")
a.appendright(3.0)
for i in a:
    print(i)`

The output I get is this:
`2.0

1.0
2.0

1.0
3.0`

Where the hell has the `2.0` gone? Weirdly, if I try the same thing after initialising with say [2.0, 4.0], everything is fine. What do you think?

**Comment by ajakubek** [comment]
Hi. That was a bug, sorry about that. I've added tests for `first` and `last` nodes in all methods which mutate the list and resolved all detected problems.
I'll release the fixes as version 0.2 later today.
