### ISSUE TITLE
Getting Error "ModuleNotFoundError: No module named 'dllist'"

### ISSUE THREAD

**Issue by senthil9091** [rgsoda/pypy-llist#5]
When I try to import pyllist in python3 "ModuleNotFoundError: No module named 'dllist'" error occurs, If I change __init__.py, the import works fine in python3. I did not try it in python2, but I guess the same will occur there as well

**Comment by ajakubek** [comment]
Python 3 was unsupported. I've just pushed a new version to master, which should fix the problem.

**Comment by senthil9091** [comment]
Thank you!!!
