### ISSUE TITLE
Incorrect behavior of dllist.remove

### ISSUE THREAD

**Issue by RuoxiQin** [rgsoda/pypy-llist#6]
The same dllistnode can be removed more than 1 time and decrease the length of dllist. For example
```
l = dllist([1, 2, 3])
tmp = l.first
l.remove(tmp)
print(len(l))
l.remove(tmp)
print(len(l))
l.remove(tmp)
print(len(l))
```

The linked list structure is correct but the length is wrong.

**Comment by ajakubek** [comment]
Thanks for reporting the issue.
Fixed in master. I'll probably push it to PyPI as version 0.3 over the weekend.

**Comment by RuoxiQin** [comment]
Thank you!
